# Assignment 4

Authors: Kamila Makhambetova

## Problem 1

### 1.1

In [1]:
import numpy as np

A = np.array([\
              [3,-1,-1,0,0,0],\
              [-1,4,-1,-1,0,0],\
              [-1,-1,4,-1,-1,0],\
              [0,-1,-1,4,-1,-1],\
              [0,0,-1,-1,4,-1],\
              [0,0,0,-1,-1,3]],float)

b = np.array([5,5,0,0,0,0],float)


def summat(A,x,i):
    n,m=np.shape(A)
    Z=np.zeros(np.shape(A))
    summ=0
    
    for j in range(0,n):
        if(i==j):
            continue
        else:
            summ=summ+A[i,j]*x[j]
    return summ

def jacobi(A,b,x,maxiter):
    x1=x
    Z=np.zeros(np.shape(A))
    x2=Z[:,0]
    n=len(np.diag(A))
    
    for m in range(0,maxiter):
        for i in range(0,n):
            x2[i]=(b[i]-summat(A,x1,i))/A[i,i]
        x1=x2
    return x2

x = np.array([0,0,0,0,0,0],float)

maxit=10
i=0

ans=jacobi(A,b,x,maxit)
print(f'approximate Vj for {maxit} iterations: \n {ans}')

b2=np.matmul(A,ans)
print(f'\n approximate b: \n {b2}')
print(f'\n given b: \n {b}')

print('\033[1m'+'\n Table 1: Jacobian method for x0=[0,0,0,0,0,0].')
print('\n {:35} {:12} \033[0m'.format('iteration','Vj'))
while i<maxit:
            print(f'{i+1:6}       {jacobi(A,b,x,i+1)}')
            i=i+1 
      

approximate Vj for 10 iterations: 
 [3.63037551 3.33649669 2.63941992 2.16069752 1.49926332 1.21998694]

 approximate b: 
 [ 4.91520991  4.91549383 -0.06915335 -0.05237681 -0.02305112  0.        ]

 given b: 
 [5. 5. 0. 0. 0. 0.]

 Table 1: Jacobian method for x0=[0,0,0,0,0,0].

 iteration                           Vj           
     1       [1.66666667 1.25       0.         0.         0.         0.        ]
     2       [2.08333333 1.77083333 0.96354167 0.68359375 0.41178385 0.36512587]
     3       [2.578125   2.3063151  1.49495443 1.14454481 0.75115628 0.63190036]
     4       [2.93375651 2.64331394 1.86819288 1.47364087 0.99343353 0.82235813]
     5       [3.17050227 2.87808401 2.12891517 1.70569771 1.16424275 0.95664682]
     6       [3.33566639 3.04256982 2.31204417 1.86887589 1.28439172 1.0510892 ]
     7       [3.45153799 3.15811451 2.44073003 1.98358137 1.36885015 1.11747717]
     8       [3.53294818 3.23931489 2.53117365 2.06420397 1.4282137  1.16413922]
     9       [3.59016

### 1.2

In [2]:
import numpy as np
A = np.array([\
             [3,-1,-1,0,0,0],\
             [-1,4,-1,-1,0,0],\
             [-1,-1,4,-1,-1,0],\
             [0,-1,-1,4,-1,-1],\
             [0,0,-1,-1,4,-1],\
             [0,0,0,-1,-1,3]], float)
b = np.array([5,5,0,0,0,0], float)

def gauss_seidel(A,b,v0,tol,imax):
    n=len(A)
    v = v0.copy()
    for i in range(imax):
        for c in range(n):
            v[c] = v0[c]
        for j in range(n):
            summ = 0
            for k in range(n):
                if k != j:
                    summ = summ + A[j][k]*v0[k]
            v0[j] = (b[j]-summ)/A[j][j]
        norm1 = 0
        norm2 = 0
        for j in range(n):
            norm1 += abs(v0[j] - v[j])
            norm2 += abs(v[j])
            if v[j] == 0:
                v[j] = 1
        norm = norm1/norm2
        if (norm<tol) and i != 0:
            print(f'{i+1} iterations')
            return v0
    
v0=np.zeros(6)
gauss_seidel(A,b,v0,0.015,10)
print(f'V_gs = {v0}')

10 iterations
V_gs = [3.65537747 3.36143587 2.66719859 2.1854602  1.51749645 1.23431888]


/Users/kamila/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:30: RuntimeWarning: divide by zero encountered in double_scalars


### 1.3

In [3]:
import numpy as np
A = np.array([\
             [3,-1,-1,0,0,0],\
             [-1,4,-1,-1,0,0],\
             [-1,-1,4,-1,-1,0],\
             [0,-1,-1,4,-1,-1],\
             [0,0,-1,-1,4,-1],\
             [0,0,0,-1,-1,3]], float)
b = np.array([5,5,0,0,0,0], float)
c = np.linalg.solve(A,b)
print('True solution = ',c)

def err1(c):
    maxit=10
    i=0
    Vj = jacobi(A,b,x,maxit)
    print(f'\n V_j = {Vj}')
    print('\n Table 1: Jacobian relative error ')
    print(' x[i]     Jacobian relative error %')
    err1 = np.zeros(6)
    for i in range(6):
        err1[i] = ((c[i]-Vj[i])/c[i])*100
        print(f' x{i}       {err1[i]}')

def err2(c):
    v0=np.zeros(6)
    tol=0.015
    imax=10
    Vgs = gauss_seidel(A,b,v0,tol,imax)
    print('\n Vgs = ',Vgs)
    print('\n Table 2: Gauss-Seidel relative error')
    print(' x[i]    Gauss-Seidel relative error %')
    err2 = np.zeros(6)
    for i in range(6):
        err2[i] = ((c[i]-Vgs[i])/c[i])*100
        print(f' x{i}       {err2[i]}')
        
err1(c)
err2(c)

True solution =  [3.7254902  3.43137255 2.74509804 2.25490196 1.56862745 1.2745098 ]

 V_j = [3.63037551 3.33649669 2.63941992 2.16069752 1.49926332 1.21998694]

 Table 1: Jacobian relative error 
 x[i]     Jacobian relative error %
 x0       2.5530784951054617
 x1       2.7649535138980252
 x2       3.849702902829627
 x3       4.177762355672845
 x4       4.421963623414546
 x5       4.277947491156631
10 iterations

 Vgs =  [3.65537747 3.36143587 2.66719859 2.1854602  1.51749645 1.23431888]

 Table 2: Gauss-Seidel relative error
 x[i]    Gauss-Seidel relative error %
 x0       1.881973135442747
 x1       2.0381546439105946
 x2       2.8377656602366295
 x3       3.0795911185367655
 x4       3.259601379696468
 x5       3.1534414820894816


/Users/kamila/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:30: RuntimeWarning: divide by zero encountered in double_scalars


## Problem 2

In [4]:
import numpy as np
A = np.array([\
              [450,-200,0],\
              [-240,420,-180],\
              [0,-225,225]], float)

def mass_spring(A):
    eigenvalue, eigenvector = np.linalg.eig(A)
    print('{:3} {:25} {:}' \
          .format('i','sqrt(ith eigenvalue)','eigenvector'))
    for i in range(1,4):
        n=0
        n = i-1
        print(f'{i} {np.sqrt(eigenvalue[n]):15.8f}           {eigenvector[:,n]}')
mass_spring(A)

i   sqrt(ith eigenvalue)      eigenvector
1     26.43100812           [-0.58785405  0.73069726 -0.34714424]
2     18.42492570           [-0.63435541 -0.3505515   0.68898973]
3      7.54479443           [0.29129699 0.57250939 0.76640659]


## Problem 3

### 3.1

In [5]:
import numpy as np
        
def summ(Q,A,i):
    n,m=np.shape(A)
    Z=np.zeros(np.shape(A))
    summ=Z[:,0]
    
    for j in range (0,i):
        summ=summ+np.dot(Q[:,j], A[:,i])*Q[:,j]
    return summ

def gramschm(A):
    n,m=np.shape(A)
    Q=np.zeros(np.shape(A))
    R=np.zeros((m,m))
    U=np.zeros(np.shape(A))
    
    for i in range (0,m):
        if (i==0):
            U[:,0]=A[:,0]
            Q[:,0]=U[:,0]/np.linalg.norm(U[:,0])
        else:
            U[:,i]=A[:,i]-summ(Q,A,i)
            Q[:,i]=U[:,i]/np.linalg.norm(U[:,i])
            
    for i in range (0,m):
        if (i==0):
            A[:,0]=Q[:,0]*np.linalg.norm(U[:,0])
            U[:,0]=Q[:,0]*np.linalg.norm(U[:,0])
        else:
            A[:,i]=Q[:,i]*np.linalg.norm(U[:,i])+summ(Q,A,i)
            U[:,i]=Q[:,i]*np.linalg.norm(U[:,i])
            
    for r in range (0,m):
        for l in range (0,m):
            if(r==l):
                 R[r,r]=np.linalg.norm(U[:,r])
            if(l>r):
                R[r,l]=np.matmul(Q[:,r],A[:,l])
    return Q,R
      

In [109]:
import numpy as np

A = np.array([\
              [-10,13,7,-11],\
              [2,1,-5,3],\
              [-6,3,13,-3],\
              [16,-16,-2,5],\
              [2,1,-5,-7]],float)

K,M=gramschm(A)  

print(f'\n the matrix Q \n')
print(K)

print(f'\n the matrix R \n')
print(M)

T=np.matmul(K,M)
print(f'\n Test: A=Q*R \n')
print(T)



 the matrix Q 

[[-5.00000000e-01  5.00000000e-01  5.77350269e-01  0.00000000e+00]
 [ 1.00000000e-01  5.00000000e-01  0.00000000e+00  7.07106781e-01]
 [-3.00000000e-01 -5.00000000e-01  5.77350269e-01 -6.28036983e-17]
 [ 8.00000000e-01  0.00000000e+00  5.77350269e-01  0.00000000e+00]
 [ 1.00000000e-01  5.00000000e-01  0.00000000e+00 -7.07106781e-01]]

 the matrix R 

[[ 20.         -20.         -10.          10.        ]
 [  0.           6.          -8.          -6.        ]
 [  0.           0.          10.39230485  -5.19615242]
 [  0.           0.           0.           7.07106781]]

 Test: A=Q*R 

[[-10.  13.   7. -11.]
 [  2.   1.  -5.   3.]
 [ -6.   3.  13.  -3.]
 [ 16. -16.  -2.   5.]
 [  2.   1.  -5.  -7.]]
